import time
print("---------------------------------------------------------------")
print ("")
print ("this program is built on newton's second law of motion(F=ma)")
print ("")
print("-----------------------------------------------------------------")
print ("")
print(" 1 is the code to find the force acting on an object")
print(" 2 is the code to find the mass of an object")
print(" 3 is the code to find the acceleration of an object")
print ("")
time.sleep(1)
print("plz enter the values in the correct units to get the correct answer")
print("")
print("unit standard- mass in kg, acceleration in m/s^2, force in Newtons")
print("")
print("-----------------------------------------------------------------")
print ("")

X=int(input("enter the code-"))

if X==1:
    print ("hmmm....")
    time.sleep(.5)
    print ("calculating...")
    time.sleep(3)   
    print("you will be using the formula F=ma")
    print("---------------------------------------------------------------------------")
  
    time.sleep(.5)  
    m=int(input("enter the mass of the object:"))
    time.sleep(.5)
    a=int(input("and also tell me the acceleration of the object:"))
    F=m*a
    time.sleep(.5)
    print("the force acting on the object is",F,"Newtons")
    time.sleep(.5) 
    print ("thank me later")

elif X==2:

    print ("hmmm....")
    time.sleep(.5)
    print ("calculating...")
    time.sleep(3)   
    print("you will be using the formula m=F/a")
    print("---------------------------------------------------------------------------")
    time.sleep(1)
    F=int(input("enter the force acting on the object:"))
    a=int(input("and also tell me the acceleration of the object:"))
    time.sleep(.5)
    m=F/a
    print("the mass of the object is",m,"kg")
    time.sleep(.5) 
    print ("thank me later")
    time.sleep(.5)
    print("---------------------------------------------------------------------------")

elif X==3:

    print ("hmmm....")
    time.sleep(.5)
    print ("calculating...")
    time.sleep(3)   
    print("you will be using the formula a=F/m")
    print("---------------------------------------------------------------------------")
    time.sleep(1)
    F=int(input("enter the force acting on the object:"))
    m=int(input("and also tell me the mass of the object:"))
    a=F/m
    print("the acceleration of the object is",a,"m/s^2")
    time.sleep(.5) 
    print ("thank me later")
    time.sleep(.5)
    print("---------------------------------------------------------------------------")

else:

    print(".")
    time.sleep(.3)   
    print(".")
    time.sleep(.3)
    print(".")
    time.sleep(.3)   
    print(".")
    time.sleep(.3)
    print(".")
    time.sleep(.3)   
    print(".")
    time.sleep(.3)
    print(".")
    time.sleep(.3)   
    print(".")
    time.sleep(1) 
    print ("error valid  code not found")
    time.sleep(2)   
    print("please restart the program and enter a valid code")
    time.sleep(2)   
    print ("---------------------------------------------------------------------------")